INVALID_REQUEST = "INVALID_REQUEST"
CASE_NOT_FOUND = "CASE_NOT_FOUND"
CASE_PROVIDER_ERROR = "CASE_PROVIDER_ERROR"
SEARCH_FAILED = "SEARCH_FAILED"
SIMPLIFICATION_FAILED = "SIMPLIFICATION_FAILED"
VALIDATION_FAILED = "VALIDATION_FAILED"
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"

ALL_ERROR_CODES = (
    INVALID_REQUEST,
    CASE_NOT_FOUND,
    CASE_PROVIDER_ERROR,
    SEARCH_FAILED,
    SIMPLIFICATION_FAILED,
    VALIDATION_FAILED,
    RATE_LIMIT_EXCEEDED,
    INTERNAL_SERVER_ERROR,
)
